"""Adiciona password

Revision ID: 02000bec2173
Revises: 957b9419d72c
Create Date: 2019-07-28 17:12:16.794131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02000bec2173'
down_revision = '957b9419d72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
