"""Adiciona coluna confirmacao

Revision ID: c596e54bdb5e
Revises: b8e7cc70a592
Create Date: 2019-08-02 23:18:14.173924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c596e54bdb5e'
down_revision = 'b8e7cc70a592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
